#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
#  nuke-and-reset.sh
#
#  Run this from ANYWHERE in the codespace.
#  It wipes /workspaces/osprey-ranger, drops in the new code,
#  injects your keys, bootstraps deps, and prepares git.
#
#  Usage:
#    bash /tmp/nuke-and-reset.sh
#
#  The script will PROMPT you for each key — just paste and press Enter.
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

CYAN='\033[0;36m'; GREEN='\033[0;32m'; RED='\033[0;31m'
YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'

box()  { echo -e "\n${CYAN}${BOLD}━━━  $1  ━━━${NC}"; }
ok()   { echo -e "  ${GREEN}✓ $1${NC}"; }
warn() { echo -e "  ${YELLOW}⚠ $1${NC}"; }
fail() { echo -e "\n${RED}✗ ERROR: $1${NC}\n"; exit 1; }
ask()  { echo -e "  ${CYAN}→ $1${NC}"; }

REPO="/workspaces/osprey-ranger"
ZIP_NAME="osprey-ranger-v2.zip"

# ── Find the zip ───────────────────────────────────────────────────────────────
box "1 / 6  Locating zip"

ZIP_PATH=""
for loc in \
  "$HOME/$ZIP_NAME" \
  "/tmp/$ZIP_NAME" \
  "/workspaces/$ZIP_NAME" \
  "$REPO/$ZIP_NAME" \
  "/workspaces/osprey-ranger-v2/$ZIP_NAME"; do
  if [ -f "$loc" ]; then
    ZIP_PATH="$loc"
    ok "Found zip at: $ZIP_PATH"
    break
  fi
done

if [ -z "$ZIP_PATH" ]; then
  echo ""
  echo -e "${RED}Could not find $ZIP_NAME${NC}"
  echo ""
  echo "  Please upload the zip to the codespace first:"
  echo "  - In VS Code: drag the zip into the Explorer panel"
  echo "  - Or via CLI: gh cs cp osprey-ranger-v2.zip remote:/tmp/"
  echo ""
  echo "  Then run this script again."
  exit 1
fi

# ── Collect keys BEFORE wiping ─────────────────────────────────────────────────
box "2 / 6  Enter your new credentials"
echo ""
echo -e "${YELLOW}  Paste your keys below. Press Enter after each one.${NC}"
echo -e "${YELLOW}  Leave blank to skip (you can fill keeper/.env manually later).${NC}"
echo ""

ask "ADMIN_KEYPAIR (the [135,100,...] array):"
read -r ADMIN_KEYPAIR

ask "MANAGER_KEYPAIR (the [136,46,...] array):"
read -r MANAGER_KEYPAIR

ask "HL_PRIVATE_KEY (0x...):"
read -r HL_PRIVATE_KEY

ask "HL_WALLET_ADDRESS (0x...):"
read -r HL_WALLET_ADDRESS

ask "DATABASE_URL (postgresql://...):"
read -r DATABASE_URL

ask "RPC_URL (https://mainnet.helius-rpc.com/?api-key=...):"
read -r RPC_URL

ask "KAMINO_ADAPTOR_PROGRAM_ID (leave blank if unsure):"
read -r KAMINO_ADAPTOR_PROGRAM_ID

ask "TRUSTFUL_ADAPTOR_PROGRAM_ID (leave blank if unsure):"
read -r TRUSTFUL_ADAPTOR_PROGRAM_ID

ask "KAMINO_COUNTER_PARTY_TA (leave blank if unsure):"
read -r KAMINO_COUNTER_PARTY_TA

ask "KAMINO_COUNTER_PARTY_TA_AUTH (leave blank if unsure):"
read -r KAMINO_COUNTER_PARTY_TA_AUTH

ask "KAMINO_PROTOCOL_PROGRAM (leave blank if unsure):"
read -r KAMINO_PROTOCOL_PROGRAM

# ── Wipe and rebuild ────────────────────────────────────────────────────────────
box "3 / 6  Wiping $REPO"

# Save .git if it exists (preserves GitHub remote, branch, history)
SAVED_GIT=""
if [ -d "$REPO/.git" ]; then
  warn ".git found — moving aside so we can re-attach it after extract"
  mv "$REPO/.git" "/tmp/osprey-git-backup"
  SAVED_GIT="/tmp/osprey-git-backup"
fi

# Wipe everything else
rm -rf "$REPO"
mkdir -p "$REPO"
ok "Wiped $REPO"

# ── Extract ────────────────────────────────────────────────────────────────────
box "4 / 6  Extracting"

cd /tmp
rm -rf osprey-extract-tmp
unzip -q "$ZIP_PATH" -d osprey-extract-tmp

# The zip contains osprey-ranger-clean/ at the top level
if [ -d osprey-extract-tmp/osprey-ranger-clean ]; then
  cp -r osprey-extract-tmp/osprey-ranger-clean/. "$REPO/"
elif [ -d "osprey-extract-tmp/osprey-ranger-v2" ]; then
  cp -r osprey-extract-tmp/osprey-ranger-v2/. "$REPO/"
else
  # Try direct contents
  cp -r osprey-extract-tmp/. "$REPO/"
fi

rm -rf osprey-extract-tmp
ok "Extracted to $REPO"

# Restore .git
if [ -n "$SAVED_GIT" ] && [ -d "$SAVED_GIT" ]; then
  mv "$SAVED_GIT" "$REPO/.git"
  ok ".git restored"
fi

cd "$REPO"

# ── Write .env ─────────────────────────────────────────────────────────────────
box "5 / 6  Writing .env files"

# keeper/.env
cat > "$REPO/keeper/.env" << ENVEOF
# Keeper Bot — Environment Variables
# Generated by nuke-and-reset.sh — $(date -u +"%Y-%m-%d %H:%M UTC")
# ─────────────────────────────────────────────────────────────────────────────
# Fill in every value before running npm run dev or deploying to Render.
# NEVER commit this file — it is in .gitignore.
# ─────────────────────────────────────────────────────────────────────────────

# Solana RPC — get a free key at helius.dev
RPC_URL=${RPC_URL:-https://mainnet.helius-rpc.com/?api-key=YOUR_HELIUS_KEY}

# Solana keypairs — JSON arrays (64 bytes) from solana-keygen new
ADMIN_KEYPAIR=${ADMIN_KEYPAIR:-}
MANAGER_KEYPAIR=${MANAGER_KEYPAIR:-}

# On-chain addresses — populated AFTER running vault-setup scripts 01–07
# Leave blank until vault-setup is complete; keeper will warn on startup.
VAULT_ADDRESS=
KAMINO_STRATEGY_ADDRESS=
TRUSTFUL_STRATEGY_ADDRESS=

# Standard Solana token addresses (safe as-is for mainnet)
USDC_MINT=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
HL_API_URL=https://api.hyperliquid.xyz
OSPREY_API_URL=https://osprey-three.vercel.app

# Hyperliquid EVM wallet — used for signing orders server-side
# Generate: npx ethers repl → ethers.Wallet.createRandom()
HL_PRIVATE_KEY=${HL_PRIVATE_KEY:-0x}
HL_WALLET_ADDRESS=${HL_WALLET_ADDRESS:-0x}

# Postgres database — create a free project at supabase.com
DATABASE_URL=${DATABASE_URL:-postgresql://postgres:PASSWORD@db.YOUR_PROJECT.supabase.co:5432/postgres}

# Adaptor program IDs — VERIFY from docs.ranger.finance/security/deployed-programs
KAMINO_ADAPTOR_PROGRAM_ID=${KAMINO_ADAPTOR_PROGRAM_ID:-}
TRUSTFUL_ADAPTOR_PROGRAM_ID=${TRUSTFUL_ADAPTOR_PROGRAM_ID:-}

# Kamino pool counterparty accounts — VERIFY from github.com/voltrxyz/kamino-scripts
KAMINO_COUNTER_PARTY_TA=${KAMINO_COUNTER_PARTY_TA:-}
KAMINO_COUNTER_PARTY_TA_AUTH=${KAMINO_COUNTER_PARTY_TA_AUTH:-}
KAMINO_PROTOCOL_PROGRAM=${KAMINO_PROTOCOL_PROGRAM:-}
ENVEOF

ok "keeper/.env written"

# vault-setup/.env — seed from example then inject shared keypairs
cp "$REPO/vault-setup/.env.example" "$REPO/vault-setup/.env"
# Inject keypairs if provided (sed replaces the placeholder lines)
[ -n "$ADMIN_KEYPAIR" ]   && sed -i "s|^ADMIN_KEYPAIR=\$|ADMIN_KEYPAIR=${ADMIN_KEYPAIR}|"     "$REPO/vault-setup/.env"
[ -n "$MANAGER_KEYPAIR" ] && sed -i "s|^MANAGER_KEYPAIR=\$|MANAGER_KEYPAIR=${MANAGER_KEYPAIR}|" "$REPO/vault-setup/.env"
[ -n "$RPC_URL" ]         && sed -i "s|^RPC_URL=https://api.devnet.*|RPC_URL=${RPC_URL}|"       "$REPO/vault-setup/.env"
ok "vault-setup/.env written"

# ── Bootstrap deps ─────────────────────────────────────────────────────────────
box "6 / 6  Installing dependencies"

cd "$REPO/keeper"
npm install 2>&1 | tail -3
ok "keeper deps installed"

cd "$REPO/vault-setup"
npm install 2>&1 | tail -3
ok "vault-setup deps installed"

# Python venv if available
if command -v python3 &>/dev/null; then
  PY_MINOR=$(python3 -c "import sys; print(sys.version_info.minor)" 2>/dev/null || echo "0")
  if [ "$PY_MINOR" -ge 11 ]; then
    cd "$REPO/quant"
    [ ! -d venv ] && python3 -m venv venv
    source venv/bin/activate
    pip install -q --upgrade pip
    pip install -q -r requirements.txt
    deactivate
    ok "Python quant deps installed"
  fi
fi

# ── Git setup ─────────────────────────────────────────────────────────────────
cd "$REPO"

if [ ! -d .git ]; then
  git init -b main
  ok "git init"
fi

# Make sure .gitignore is committed first so secrets aren't staged
git add .gitignore
git commit -m "chore: add .gitignore" --allow-empty -q 2>/dev/null || true

# Stage everything (secrets excluded by .gitignore)
git add -A
git status --short | head -20

echo ""
echo -e "${GREEN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}${BOLD}  Done! Repo is ready at $REPO ${NC}"
echo -e "${GREEN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  Next:"
echo ""
echo -e "  ${CYAN}1.${NC} Review: ${YELLOW}cat keeper/.env${NC}"
echo -e "  ${CYAN}2.${NC} Open SETUP.md: ${YELLOW}cat SETUP.md | head -60${NC}"
echo -e "  ${CYAN}3.${NC} Commit and push:"
echo ""
echo -e "     ${YELLOW}cd $REPO"
echo -e "     git commit -m \"feat: osprey-ranger v2 — clean slate\""
echo -e "     git remote add origin https://github.com/Xtley001/osprey-ranger.git  # skip if already set"
echo -e "     git push -u origin main --force${NC}"
echo ""
echo -e "  ${CYAN}4.${NC} Start the keeper (dev mode):"
echo -e "     ${YELLOW}cd keeper && npm run dev${NC}"
echo ""
